### ISSUE TITLE
[bug]: API - Internal server error 500

### ISSUE THREAD

**Issue by danardf** [FreePBX/api#13]
### FreePBX Version

FreePBX 17

### Issue Description

Unable to get token.
And a simple RestAPI request returns and error 500.

No way to use APIs on 17. 

### Operating Environment

FreePBX 17 version updated. 

### Relevant log output

```shell
{
	"error": {
		"type": "TypeError",
		"message": "Slim\\App::__construct(): Argument #1 ($responseFactory) must be of type Psr\\Http\\Message\\ResponseFactoryInterface, array given, called in \/var\/www\/html\/admin\/modules\/api\/Rest\/Api.php on line 49",
		"code": 0,
		"file": "\/var\/www\/html\/admin\/libraries\/Composer\/vendor\/slim\/slim\/Slim\/App.php",
		"line": 47
	}
}
```
```

**Comment by dolesec** [comment]
I see the same

**Comment by danardf** [comment]
> I see the same

@kguptasangoma is aware now.

**Comment by kapilgupta01** [comment]
Yes due to latest Slim lib updates, GQL API got the updated compatible code , same needs to be done for the Rest API.

will try to fix this asap. 

Thanks

**Comment by danardf** [comment]
> Yes due to latest Slim lib updates, GQL API got the updated compatible code , same needs to be done for the Rest API.
> 
> will try to fix this asap.
> 
> Thanks

Nice.
but it's not only with ResetAPI.
There is no way to get the token as well.

**Comment by kapilgupta01** [comment]
Please update all your modules to the edge and give a try. Thanks

**Comment by danardf** [comment]
@kguptasangoma Ok I will test it tomorrow morning in my timezone and I will update you soon.
Thanks for your time Kapil.

**Comment by danardf** [comment]
@kguptasangoma Hey  Kapil
It doesn't work.
Please check your email
