### ISSUE TITLE
[bug]: Whoops\Exception Creation of dynamic property FreePBX\Console\Command\Api::$input is deprecated

### ISSUE THREAD

**Issue by Rverma032** [FreePBX/api#16]
### FreePBX Version

FreePBX 17

### Issue Description

CLI command fails with the below error: fwconsole api gql genclientcred

In Api.class.php line 30:
  [Whoops\Exception\ErrorException (8192)]
  Creation of dynamic property FreePBX\Console\Command\Api::$input is deprecated

### Operating Environment

API 17.0.1.2

**Comment by kapilgupta01** [comment]
api v17.0.1.3
