### ISSUE TITLE
[bug]: API GQL/Core: Delete Extension doesn't set Need Reload. 

### ISSUE THREAD

**Issue by danardf** [FreePBX/api#8]
### FreePBX Version

FreePBX 16

### Issue Description

When you delete an extension, Need Reload is not set, however, if you delete an extension through GUI, need reload is set. (You can see Apply Config button). 
This action with API should execute the same action as the GUI. 
Just set needreload = true at the end of the API for delete extension. 

This difference is importent if the changes are not applied after deletion and if there is no way to know if the system needs reloading. 

### Operating Environment

framework: 16.0.40.7
api: 16.0.13
core: 16.0.68.24

**Comment by kapilgupta01** [comment]
fixed, try with the latest version.

**Comment by danardf** [comment]
Nice.

Thanks Kapil
